### ISSUE TITLE
Not the correct schema

### ISSUE THREAD

**Issue by shatodj** [Raistlfiren/FAIconFieldType#8]
Hello. I'm trying out your plugin.  I'm having some problem with DB schema after adding the field into `contenttypes.yml`:
```
Table bolt_blocks is not the correct schema: invalid column icon
Update the database
```
After clicking update nothing changes. 
Here is my `contenttypes.yml`:
```
blocks:
    name: Blocks
    singular_name: Block
    fields:
        icon:
            type: faiconpicker
            hidden: false
        title:
            type: text
            class: large
            group: "Block"
        slug:
            type: slug
            uses: [ title ]
        content:
            type: html
            height: 150px
        contentlink:
            type: text
            label: Link
            placeholder: 'contenttype/slug or http://example.org/'
            postfix: "Use this to add a link for this Block. This could either be an 'internal' link like <tt>page/about</tt>, if you use a contenttype/slug combination. Otherwise use a proper URL, like `http://example.org`."
        image:
            type: image
            attrib: title
            extensions: [ gif, jpg, png ]
    show_on_dashboard: true
    viewless: true
    default_status: published
    searchable: false
    icon_many: "fa:cubes"
    icon_one: "fa:cube"
```
Also saving the content doesn't work.
Is this plugin issue or am I doing something wrong? Thanks for your help.
